services:
  - type: web
    name: ai-article-generator
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: FLASK_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: ai-article-generator
          property: port